### ISSUE TITLE
What does "(☆^O^☆) " do?

### ISSUE THREAD

**Issue by Lebon14** [authorblues/smwrandomizer#45]
Self-explanatory. There's no documentation readily avaialable that explains how it works.
Can somebody tell me? Thanks!

**Comment by authorblues** [comment]
(☆^O^☆)

**Comment by authorblues** [comment]
It is a collection of miscellaneous features.

**Comment by Lebon14** [comment]
Miscellaneous features? What kind of features? Is it like the random% in the LoZ rando? This is so vague... it doesn't really answer my question.

**Comment by authorblues** [comment]
Sorry, it is just a collection of really minor changes that don't fit in any other category.

- Randomize what extended sprite hammer bro throws
- Randomize the sprite fishin lakitu carries
- Randomize ball & chain and spinning platform speed
- Randomize sprite in switch palace switch room
- Change a few sound effects and occasionally randomize sound effects
- Randomize a few cosmetic features in some levels

**Comment by jmatch83** [comment]
Glad I wasn't the only one curious about what this did.  Maybe something next to which describes, like: (☆^O^☆) - misc. minor sprite/sound randomizations.
Good to know that this is what caused the spinning platform (and I assume block snake) to go faster in the seed I generated.  I selected it simply because it looked like a joyous sprinkle of fun (☆^o^☆)
