### ISSUE TITLE
Impossible stage!

### ISSUE THREAD

**Issue by OwenGrenn** [authorblues/smwrandomizer#48]
ROM: http://authorblues.github.io/smwrandomizer/#!/13794794/8 (edae)

The level that was supposed to be Yoshi's Island 3 is unbeatable!
At the end is a pipe, no goal, and it leads me to a bonus room.
The pipe at the top of the room leads to exactly to the same level I was on before! There was no goals at all!

**Comment by authorblues** [comment]
You may want to check and make sure that there are no other pipes in the
stage. Best of luck!

On Jul 25, 2017 2:29 PM, "OwenGrenn" <notifications@github.com> wrote:

ROM: http://authorblues.github.io/smwrandomizer/#!/13794794/8 (edae)

The level that was supposed to be Yoshi's Island 3 is unbeatable!
At the end is a pipe, no goal, and it leads me to a bonus room.
The pipe at the top of the room leads to exactly to the same level I was on
before! There was no goals at all!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/authorblues/smwrandomizer/issues/48>, or mute the thread

**Comment by EnderofGames** [comment]
The pipe that leads to the end is very quickly into the level, and is in a place where a subworld would be if it were the vanilla level. This is an option in the randomizer interface. 

The level in the overworld that represents Yoshi's Island 3:
<img width="754" alt="overworld snip" src="https://user-images.githubusercontent.com/17417666/30675958-d6687470-9e40-11e7-9de0-85f185177d3f.PNG">

The pipe that contains the goal tape:
<img width="749" alt="pipe of interest" src="https://user-images.githubusercontent.com/17417666/30676130-b337de5e-9e41-11e7-96cc-92314213545b.PNG">

Through the pipe:
<img width="751" alt="the other side" src="https://user-images.githubusercontent.com/17417666/30676141-c4adf894-9e41-11e7-96c6-865a9a161885.PNG">


This issue can be closed.

**Comment by authorblues** [comment]
Thanks @EnderofGames
